steps:
  - name: 'gradle:7.5.0-jdk17-alpine'
    args: [ 'build' ]
    entrypoint: gradle
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=europe-central2-docker.pkg.dev/$PROJECT_ID/music-explorer-repo/music-explorer:$SHORT_SHA', '.' ]
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "europe-central2-docker.pkg.dev/$PROJECT_ID/music-explorer-repo/music-explorer:$SHORT_SHA" ]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args: ['run', '--filename=k8s', '--image=europe-central2-docker.pkg.dev/$PROJECT_ID/music-explorer-repo/music-explorer:$SHORT_SHA', '--location=europe-central2', '--cluster=music-explorer-cluster']