steps:
  - id: Gradle build
    name: 'gradle:7.5.0-jdk17-alpine'
    args: [ 'build' ]
    entrypoint: gradle
  - id: Build Docker image
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=europe-central2-docker.pkg.dev/$PROJECT_ID/music-explorer-repo/music-explorer', '.' ]
  - id: Push Docker image
    name: "gcr.io/cloud-builders/docker"
    args: [ "push", "europe-central2-docker.pkg.dev/$PROJECT_ID/music-explorer-repo/music-explorer" ]
  - id: Deploy to GKE
    name: "gcr.io/cloud-builders/gke-deploy"
    args: ['run', '--filename=k8s', '--location=europe-central2', '--cluster=music-explorer-cluster']