steps:
  - name: 'gradle:7.5.0-jdk17-alpine'
    args: ['build']
    entrypoint: gradle
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=europe-central2-docker.pkg.dev/$PROJECT_ID/music-explorer-repo/music-explorer', '.']
images: ['europe-central2-docker.pkg.dev/$PROJECT_ID/music-explorer-repo/music-explorer']