server:
  port: ${PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '"8&*$c}?2%U?j>Fy'
  cloud.gcp.sql:
    instance-connection-name: learngcp-353414:europe-central2:artists-db
    database-name: postgres

---
spring.config.activate.on-profile: local

spring.cloud.gcp:
  sql.enabled: false
  core.enabled: false

spring:
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: off

spring.liquibase.change-log: classpath:liquibase/changelog.xml

server.port: 8080

---
spring.config.activate.on-profile: local-postgres

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testpassword
  jpa:
    generate-ddl: off