server:
  port: ${PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: on

---
spring.config.activate.on-profile: local-postgres

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testpassword
  jpa:
    generate-ddl: off

server:
  port: 8080