server:
  port: ${PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 3
  cloud.gcp.sql:
    instance-connection-name: ${DB_CONNECTION_NAME}
    database-name: ${DB_NAME}
  jpa:
    generate-ddl: off

pubsub.imagesToLoad.topic.name: ImagesToLoad

---
spring.config.activate.on-profile: local

spring:
  cloud.gcp:
    sql.enabled: false
    core.enabled: true
    storage.enabled: true
  datasource:
    driver-class-name: org.h2.Driver

server.port: 8080

---
spring.config.activate.on-profile: local-postgres

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres