apiVersion: "v1"
kind: "Secret"
data:
  db-username: "cG9zdGdyZXM="
  db-password: "IjgmKiRjfT8yJVU/aj5GeQ=="
  db-name: "cG9zdGdyZXM="
  db-connection-name: "bGVhcm5nY3AtMzUzNDE0OmV1cm9wZS1jZW50cmFsMjphcnRpc3RzLWRi"
metadata:
  name: "db-secret"