apiVersion: v1
kind: Service
metadata:
  labels:
    app: music-explorer
  name: music-explorer-service
spec:
  ports:
    - nodePort: 30521
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: music-explorer
  type: LoadBalancer